/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SignInIndexImport } from './routes/sign-in/index'
import { Route as MyCompilsIndexImport } from './routes/my-compils/index'
import { Route as CompilsIndexImport } from './routes/compils/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignInIndexRoute = SignInIndexImport.update({
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const MyCompilsIndexRoute = MyCompilsIndexImport.update({
  path: '/my-compils/',
  getParentRoute: () => rootRoute,
} as any)

const CompilsIndexRoute = CompilsIndexImport.update({
  path: '/compils/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/compils/': {
      id: '/compils/'
      path: '/compils'
      fullPath: '/compils'
      preLoaderRoute: typeof CompilsIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-compils/': {
      id: '/my-compils/'
      path: '/my-compils'
      fullPath: '/my-compils'
      preLoaderRoute: typeof MyCompilsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CompilsIndexRoute,
  MyCompilsIndexRoute,
  SignInIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/compils/",
        "/my-compils/",
        "/sign-in/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/compils/": {
      "filePath": "compils/index.tsx"
    },
    "/my-compils/": {
      "filePath": "my-compils/index.tsx"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
